version: "3"

vars:
  GIT_TAG:
    sh: git describe --tags --always --dirty="-dev"
  GO_BIN: "{{.ROOT_DIR}}/bin"
  GO_PATH:
    sh: "go env GOPATH | awk -F: '{print $1}'"
  BUILD_TIME:
    sh: TZ='Asia/Shanghai' date "+%Y-%m-%d-%H-%M-%S"

  LDFLAGS: "-s -w"

includes:
  build:
    taskfile: ./hack/taskfile/build.yaml
    flatten: true
  lint:
    taskfile: ./hack/taskfile/lint.yaml
    flatten: true
  deps:
    taskfile: ./hack/taskfile/deps.yaml
    flatten: true
  test:
    taskfile: ./hack/taskfile/test.yaml
    flatten: true

tasks:
  default:
    desc: 列出所有任务
    cmds:
      - task --list-all
    silent: true

  proto:
    desc: 从 proto 生成 gRPC 代码
    cmds:
      - mkdir -p api/tunnel
      - |
        protoc \
          --go_out=api/tunnel \
          --go_opt=paths=source_relative \
          --go-grpc_out=api/tunnel \
          --go-grpc_opt=paths=source_relative \
          -I api/proto \
          api/proto/tunnel.proto
    sources:
      - api/proto/tunnel.proto
    generates:
      - api/tunnel/*.go

  clean:
    desc: 删除编译产物
    cmds:
      - rm -rf {{.GO_BIN}}
